/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practicamp;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aserr
 */
public class NuevoEsbirro extends javax.swing.JPanel {
    private GestionEsbirros gEsbirros;
    private int btnPulsado; // 1 si se pulsa Humano, 2 si Demonio y 3 si Ghoul
    /**
     * Creates new form NuevoEsbirro
     */
    public NuevoEsbirro(GestionEsbirros gEsbirros) {
        this.gEsbirros = gEsbirros;
        initComponents();
        this.actualizarInfo();
    }
    
    public void actualizarInfo(){
        this.btnPulsado = 0;
        etiqNombre.setVisible(false);
        textNombre.setText("");
        textNombre.setVisible(false);
        etiqSalud.setVisible(false);
        opSalud.setVisible(false);
        etiqLealtad.setVisible(false);
        opLealtad.setVisible(false);
        etiqDependencia.setVisible(false);
        opDependencia.setVisible(false);
        etiqPacto.setVisible(false);
        textPacto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHumano = new javax.swing.JButton();
        btnDemonio = new javax.swing.JButton();
        btnGhoul = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        textNombre = new javax.swing.JTextField();
        etiqNombre = new javax.swing.JLabel();
        opSalud = new javax.swing.JComboBox<>();
        etiqSalud = new javax.swing.JLabel();
        opLealtad = new javax.swing.JComboBox<>();
        etiqLealtad = new javax.swing.JLabel();
        opDependencia = new javax.swing.JComboBox<>();
        etiqDependencia = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        textPacto = new javax.swing.JTextField();
        etiqPacto = new javax.swing.JLabel();

        btnHumano.setText("Humano");
        btnHumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHumanoActionPerformed(evt);
            }
        });

        btnDemonio.setText("Demonio");
        btnDemonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemonioActionPerformed(evt);
            }
        });

        btnGhoul.setText("Ghoul");
        btnGhoul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhoulActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        etiqNombre.setText("Nombre :");

        opSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        etiqSalud.setText("Salud :");

        opLealtad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALTA", "NORMAL", "BAJA" }));

        etiqLealtad.setText("Lealtad :");

        opDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        etiqDependencia.setText("Dependencia :");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        textPacto.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        etiqPacto.setText("Pacto :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnHumano, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnDemonio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnGhoul, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqNombre)
                                    .addComponent(etiqSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiqLealtad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opLealtad, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(textPacto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(etiqPacto))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(450, 450, 450)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHumano, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDemonio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGhoul, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(etiqNombre)
                                .addGap(54, 54, 54)
                                .addComponent(etiqSalud)
                                .addGap(44, 44, 44)
                                .addComponent(etiqLealtad)
                                .addGap(44, 44, 44)
                                .addComponent(etiqDependencia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(opSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(opLealtad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(opDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiqPacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPacto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHumanoActionPerformed
        this.actualizarInfo();
        this.btnPulsado = 1;
        etiqNombre.setVisible(true);
        textNombre.setVisible(true);
        etiqSalud.setVisible(true);
        opSalud.setVisible(true);
        etiqLealtad.setVisible(true);
        opLealtad.setVisible(true);
        
    }//GEN-LAST:event_btnHumanoActionPerformed

    private void btnDemonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemonioActionPerformed
        this.actualizarInfo();
        this.btnPulsado = 2;
        etiqNombre.setVisible(true);
        textNombre.setVisible(true);
        etiqSalud.setVisible(true);
        opSalud.setVisible(true);
        etiqPacto.setVisible(true);
        textPacto.setVisible(true);
    }//GEN-LAST:event_btnDemonioActionPerformed

    private void btnGhoulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhoulActionPerformed
        this.actualizarInfo();
        this.btnPulsado = 3;
        etiqNombre.setVisible(true);
        textNombre.setVisible(true);
        etiqSalud.setVisible(true);
        opSalud.setVisible(true);
        etiqDependencia.setVisible(true);
        opDependencia.setVisible(true);
    }//GEN-LAST:event_btnGhoulActionPerformed
    
    public Esbirro crearEsbirro(String nombre){
        int salud = Integer.parseInt(opSalud.getSelectedItem().toString());
        Esbirro esbirro;
        if (this.btnPulsado == 2){
            String pacto = textPacto.getText();
            esbirro = new Demonio(nombre, salud,null,pacto);
        } else if (btnPulsado == 1){
            String eleccion = opLealtad.getSelectedItem().toString();
            Lealtad lealtad = null;
            if (eleccion.equals("ALTA")){
                lealtad = lealtad.alta;
            } else if(eleccion.equals("NORMAL")){
                    lealtad = lealtad.media;
            } else {
                lealtad = lealtad.baja;
            }
            esbirro = new Humano(nombre, salud,lealtad);
        } else{
            int dependencia = Integer.parseInt(opDependencia.getSelectedItem().toString());
            esbirro = new Ghoul(nombre, salud, dependencia);
        }
        return esbirro;   
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String nombre = textNombre.getText();
        if ((!"".equals(nombre)) && (this.btnPulsado != 0)){
            Esbirro esbirro = crearEsbirro(nombre);
            if (gEsbirros.getNivel() != 0){
                Esbirro esbirroSeleccionado = gEsbirros.getEsbirroSeleccionado();
                Demonio demonioSeleccionado = (Demonio) esbirroSeleccionado;
                demonioSeleccionado.addEsbirro(esbirro);
            } else {
                gEsbirros.addEsbirro(esbirro);
            }
        
        JPanel parent = (JPanel) getParent();
        CardLayout cl = (CardLayout) parent.getLayout();
        cl.show(parent, "gestionEsbirros");
        this.actualizarInfo();
        gEsbirros.añadirInfo(gEsbirros.getNombrePersonaje());
        } else if("".equals(nombre)){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un nombre");
        } else if(this.btnPulsado == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una opción");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        JPanel parent = (JPanel) getParent();
        CardLayout cl = (CardLayout) parent.getLayout();
        cl.show(parent, "gestionEsbirros");
        this.actualizarInfo();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnDemonio;
    private javax.swing.JButton btnGhoul;
    private javax.swing.JButton btnHumano;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel etiqDependencia;
    private javax.swing.JLabel etiqLealtad;
    private javax.swing.JLabel etiqNombre;
    private javax.swing.JLabel etiqPacto;
    private javax.swing.JLabel etiqSalud;
    private javax.swing.JComboBox<String> opDependencia;
    private javax.swing.JComboBox<String> opLealtad;
    private javax.swing.JComboBox<String> opSalud;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPacto;
    // End of variables declaration//GEN-END:variables
}
