/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practicamp;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aserr
 */
public class NuevoEsbirro extends javax.swing.JPanel {
    private GestionEsbirros gEsbirros;
    private int btnPulsado; // 1 si se pulsa Humano, 2 si Demonio y 3 si Ghoul
    /**
     * Creates new form NuevoEsbirro
     */
    public NuevoEsbirro(GestionEsbirros gEsbirros) {
        this.gEsbirros = gEsbirros;
        initComponents();
        this.actualizarInfo();
    }
    
    public void actualizarInfo(){
        this.btnPulsado = 0;
        etiqNombre.setVisible(false);
        textNombre.setText("");
        textNombre.setVisible(false);
        etiqSalud.setVisible(false);
        opSalud.setVisible(false);
        etiqLealtad.setVisible(false);
        opLealtad.setVisible(false);
        etiqDependencia.setVisible(false);
        opDependencia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHumano = new javax.swing.JButton();
        btnDemonio = new javax.swing.JButton();
        btnGhoul = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        textNombre = new javax.swing.JTextField();
        etiqNombre = new javax.swing.JLabel();
        opSalud = new javax.swing.JComboBox<>();
        etiqSalud = new javax.swing.JLabel();
        opLealtad = new javax.swing.JComboBox<>();
        etiqLealtad = new javax.swing.JLabel();
        opDependencia = new javax.swing.JComboBox<>();
        etiqDependencia = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        btnHumano.setText("Humano");
        btnHumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHumanoActionPerformed(evt);
            }
        });

        btnDemonio.setText("Demonio");
        btnDemonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemonioActionPerformed(evt);
            }
        });

        btnGhoul.setText("Ghoul");
        btnGhoul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhoulActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        etiqNombre.setText("Nombre :");

        opSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        etiqSalud.setText("Salud :");

        opLealtad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALTA", "NORMAL", "BAJA" }));

        etiqLealtad.setText("Lealtad :");

        opDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        etiqDependencia.setText("Dependencia :");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(btnHumano, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnDemonio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnGhoul)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etiqNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiqSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiqLealtad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(etiqDependencia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNombre)
                            .addComponent(opSalud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opLealtad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDemonio, btnGhoul, btnHumano});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAceptar, btnVolver});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDemonio, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnGhoul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHumano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombre))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqSalud))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opLealtad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqLealtad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqDependencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDemonio, btnGhoul, btnHumano});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {opDependencia, opLealtad, opSalud, textNombre});

    }// </editor-fold>//GEN-END:initComponents

    private void btnHumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHumanoActionPerformed
        this.actualizarInfo();
        this.btnPulsado = 1;
        etiqNombre.setVisible(true);
        textNombre.setVisible(true);
        etiqSalud.setVisible(true);
        opSalud.setVisible(true);
        etiqLealtad.setVisible(true);
        opLealtad.setVisible(true);
        
    }//GEN-LAST:event_btnHumanoActionPerformed

    private void btnDemonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemonioActionPerformed
        this.actualizarInfo();
        this.btnPulsado = 2;
        etiqNombre.setVisible(true);
        textNombre.setVisible(true);
        etiqSalud.setVisible(true);
        opSalud.setVisible(true);
    }//GEN-LAST:event_btnDemonioActionPerformed

    private void btnGhoulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhoulActionPerformed
        this.actualizarInfo();
        this.btnPulsado = 3;
        etiqNombre.setVisible(true);
        textNombre.setVisible(true);
        etiqSalud.setVisible(true);
        opSalud.setVisible(true);
        etiqDependencia.setVisible(true);
        opDependencia.setVisible(true);
    }//GEN-LAST:event_btnGhoulActionPerformed
    
    public Esbirro crearEsbirro(String nombre){
        int salud = Integer.parseInt(opSalud.getSelectedItem().toString());
        Esbirro esbirro;
        if (this.btnPulsado == 2){
            esbirro = new Demonio(nombre, salud,null,"");
        } else if (btnPulsado == 1){
            String eleccion = opLealtad.getSelectedItem().toString();
            Lealtad lealtad = null;
            if (eleccion.equals("ALTA")){
                lealtad = lealtad.alta;
            } else if(eleccion.equals("NORMAL")){
                    lealtad = lealtad.media;
            } else {
                lealtad = lealtad.baja;
            }
            esbirro = new Humano(nombre, salud,lealtad);
        } else{
            int dependencia = Integer.parseInt(opDependencia.getSelectedItem().toString());
            esbirro = new Ghoul(nombre, salud, dependencia);
        }
        return esbirro;   
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String nombre = textNombre.getText();
        if ((!"".equals(nombre)) && (this.btnPulsado != 0)){
            Esbirro esbirro = crearEsbirro(nombre);
            if (gEsbirros.getNivel() != 0){
                gEsbirros.setEsbirroSeleccionado(esbirro);
            } else {
                gEsbirros.addEsbirro(esbirro);
            }
        JPanel parent = (JPanel) getParent();
        CardLayout cl = (CardLayout) parent.getLayout();
        cl.show(parent, "gestionEsbirros");
        this.actualizarInfo();
        } else if("".equals(nombre)){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un nombre");
        } else if(this.btnPulsado == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una opción");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        JPanel parent = (JPanel) getParent();
        CardLayout cl = (CardLayout) parent.getLayout();
        cl.show(parent, "gestionEsbirros");
        this.actualizarInfo();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnDemonio;
    private javax.swing.JButton btnGhoul;
    private javax.swing.JButton btnHumano;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel etiqDependencia;
    private javax.swing.JLabel etiqLealtad;
    private javax.swing.JLabel etiqNombre;
    private javax.swing.JLabel etiqSalud;
    private javax.swing.JComboBox<String> opDependencia;
    private javax.swing.JComboBox<String> opLealtad;
    private javax.swing.JComboBox<String> opSalud;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
